server:
  port: 9001
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.86.157:1111
management:
  endpoints:
    web:
      exposure:
        include: "*"